<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>promise其他方法的实现</title>
</head>

<body>
    <!-- 
        Promsie.resolve(value) 可以将任何值转成值为 value 状态是 fulfilled 的 Promise，
        但如果传入的值本身是 Promise 则会原样返回它。
     -->
    <script>
        Promise.resolve = function (value) {
            // 如果是 Promsie，则直接输出它
            if (value instanceof Promise) {
                return value
            }
            return new Promise(resolve => resolve(value))
        }
    </script>
    <!-- 
        Promise.reject() 会实例化一个 rejected 状态的 Promise。但与 Promise.resolve() 不同的是，
        如果给 Promise.reject() 传递一个 Promise 对象，则这个对象会成为新 Promise 的值。
     -->
    <script>
        Promise.reject = function (reason) {
            return new Promise((resolve, reject) => reject(reason))
        }
    </script>

    <!-- 
        Promise.all 
          1.传入的所有 Promsie 都是 fulfilled，则返回由他们的值组成的，状态为 fulfilled 的新 Promise；
          2.只要有一个 Promise 是 rejected，则返回 rejected 状态的新 Promsie，
             且它的值是第一个 rejected 的 Promise 的值；
          3.只要有一个 Promise 是 pending，则返回一个 pending 状态的新 Promise；
     -->
    <script>
        Promise.all = function (promiseArr) {
            let index = 0, result = []
            return new Promise((resolve, reject) => {
                promiseArr.forEach((p, i) => {
                    Promise.resolve(p).then(val => {
                        index++
                        result[i] = val
                        if (index === promiseArr.length) {
                            resolve(result)
                        }
                    }, err => {
                        reject(err)
                    })
                })
            })
        }
    </script>

    <!-- 
        Promise.race 会返回一个由所有可迭代实例中第一个 fulfilled 或 rejected 的实例包装后的新实例。
     -->
    <script>
        Promise.race = function (promiseArr) {
            return new Promise((resolve, reject) => {
                promiseArr.forEach(p => {
                    Promise.resolve(p).then(val => {
                        resolve(val)
                    }, err => {
                        rejecte(err)
                    })
                })
            })
        }
    </script>

    <!-- 
        Promise.allSettled 的规则是这样：
          1.所有 Promise 的状态都变化了，那么新返回一个状态是 fulfilled 的 Promise，
             且它的值是一个数组，数组的每项由所有 Promise 的值和状态组成的对象；
          2.如果有一个是 pending 的 Promise，则返回一个状态是 pending 的新实例；
     -->
    <script>
        Promise.allSettled = function (promiseArr) {
            let result = []

            return new Promise((resolve, reject) => {
                promiseArr.forEach((p, i) => {
                    Promise.resolve(p).then(val => {
                        result.push({
                            status: 'fulfilled',
                            value: val
                        })
                        if (result.length === promiseArr.length) {
                            resolve(result)
                        }
                    }, err => {
                        result.push({
                            status: 'rejected',
                            reason: err
                        })
                        if (result.length === promiseArr.length) {
                            resolve(result)
                        }
                    })
                })
            })
        }
    </script>


    <!-- 
        Promise.any 的规则是这样：
        1.空数组或者所有 Promise 都是 rejected，则返回状态是 rejected 的新 Promsie，且值为 AggregateError 的错误；
        2.只要有一个是 fulfilled 状态的，则返回第一个是 fulfilled 的新实例；
        3.其他情况都会返回一个 pending 的新实例；
     -->
    <script>
        Promise.any = function (promiseArr) {
            let index = 0
            return new Promise((resolve, reject) => {
                if (promiseArr.length === 0) return
                promiseArr.forEach((p, i) => {
                    Promise.resolve(p).then(val => {
                        resolve(val)

                    }, err => {
                        index++
                        if (index === promiseArr.length) {
                            reject(new AggregateError('All promises were rejected'))
                        }
                    })
                })
            })
        }
    </script>

    <!-- 
        catch方法:catch方法是对then方法的封装，只用于接收reject(reason)中的错误信息。
        因为在then方法中onRejected参数是可不传的，不传的情况下，错误信息会依次往后传递，
        直到有onRejected函数接收为止，因此在写promise链式调用的时候，then方法不传onRejected函数，
        只需要在最末尾加一个catch()就可以了，这样在该链条中的promise发生的错误都会被最后的catch捕获到。
     -->
    <script>
        function catch1(onRejected) {
            return this.then(null, onRejected);
        }
    </script>

    <!-- 
        done:catch在promise链式调用的末尾调用，用于捕获链条中的错误信息，但是catch方法内部也可能出现错误，
        所以有些promise实现中增加了一个方法done，done相当于提供了一个不会出错的catch方法，
        并且不再返回一个promise，一般用来结束一个promise链。
     -->
    <script>
        function done1() {
            this.catch(reason => {
                console.log('done', reason);
                throw reason;
            });

        }
    </script>

    <!-- 
        finally:finally方法用于无论是resolve还是reject，finally的参数函数都会被执行。
     -->
    <script>
        function finally1(fn) {
            return this.then(
                value => {fn();return value; },
                reason => {fn();throw reason;});
        };

        // ES6入门文档
        Promise.prototype.finally = function (callback) {
            let P = this.constructor;
            return this.then(
                value => P.resolve(callback()).then(() => value),
                reason => P.resolve(callback()).then(() => { throw reason })
            );
        };
    </script>
</body>

</html>